---
- name: Create kamailio group
  group: 
    name: "{{ kamailio_group }}"
    state: present

- name: Create kamailio user
  user:
    name: "{{ kamailio_user }}"
    group: "{{ kamailio_group }}"
    state: present

- name: Installing useful utilities
  apt:
    update_cache: yes
    pkg:
      - tshark
      - sngrep

- name: Installing required packages
  apt:
    update_cache: yes
    pkg:
      - gcc
      - bison
      - flex
      - make
      - openssl
      - libssl-dev
      - python-pip
      - python-mysqldb
      - dbus
      - libev4
      - libevent-dev
      - mysql-client
      - libcurl4-openssl-dev

- name: Install pexpect
  pip:
    name: pexpect

- name: Remove old file
  file: path={{ kamailio_source_base_directory }}/{{ kamailio_source_filename }} state=absent

- name: Remove old directories
  file: path={{ kamailio_source_directory }} state=absent

- name: Download kamailio
  get_url:
    url: "{{ kamailio_source_url }}"
    dest: "{{ kamailio_source_base_directory }}"

- name: Unarchive kamailio
  unarchive: 
    src: "{{ kamailio_source_base_directory }}/{{ kamailio_source_filename }}"
    dest: "{{ kamailio_source_base_directory }}"
    copy: no

- name: Build kamailio
  command: "{{ item }}"
  args:
    chdir: "{{ kamailio_source_directory }}"
  with_items:
    - make include_module="db_mysql lcr http_async_client" cfg
    - make all
    - make install

- name: Copy the startup script
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: files/systemd/kamailio.service, dest: /etc/systemd/system/kamailio.service }
    - { src: files/tmpfiles/kamailio.conf, dest: /etc/tmpfiles.d/kamailio.conf }

- name: Copy the config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - { src: templates/kamailio.cfg.j2, dest: /usr/local/etc/kamailio/kamailio.cfg }
    - { src: templates/dispatcher.list.j2, dest: /usr/local/etc/kamailio/dispatcher.list }
  tags: ["kamailio_script"]

# - name: Restart the kamailio

  
# - name: Add an Apt signing key, uses whichever key is at the URL
#   apt_key:
#     url: http://deb.kamailio.org/kamailiodebkey.gpg
#     state: present

# - name: add kamilio deb repository
#   apt_repository:
#     repo: deb http://deb.kamailio.org/kamailio52 stretch main
#     state: present

# - name: add kamail deb-src repository
#   apt_repository:
#     repo: deb-src http://deb.kamailio.org/kamailio52 stretch main
#     state: present

# - name: install kamailio
#   apt: name={{item}} state=present update_cache=yes install_recommends=no
#   with_items:
#     - kamailio
