---
kamailio_version: 5.2.3

kamailio_user: kamailio
kamailio_group: kamailio

kamailio_source_filename: "kamailio-{{ kamailio_version }}_src.tar.gz"
kamailio_source_url: "https://www.kamailio.org/pub/kamailio/latest/src/{{ kamailio_source_filename }}"
kamailio_source_base_directory: /usr/local/src
kamailio_source_directory: "{{ kamailio_source_base_directory }}/kamailio-{{ kamailio_version }}"

kamailio_dispatcher_destination_port: 5060

kamailio_advertise_addr: 34.90.205.233:5060

rtpengine_lb_addr: udp:10.164.15.193:2223

# kamailio-5.2.3_src.tar.gz
# https://www.kamailio.org/pub/kamailio/latest/src/kamailio-5.2.3_src.tar.gz