---
- name: create a disk
  gcp_compute_disk:
    project: "{{ gcp_project }}"
    zone: "{{ gcp_instance_zone }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"

    name: "{{ gcp_instance_kamailio_name }}"
    size_gb: "{{ gcp_disk_size }}"
    source_image: "{{ gcp_disk_image }}"
    state: present
  register: disk

- name: create a instance
  register: instance
  gcp_compute_instance:
    project: "{{ gcp_project }}"
    zone: "{{ gcp_instance_zone }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"

    name: "{{ gcp_instance_kamailio_name }}"
    state: present
    machine_type: n1-standard-1
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
    network_interfaces:
        - access_configs:
          - name: 'External NAT'
            type: 'ONE_TO_ONE_NAT'
    tags:
      items:
        - kamailio


# ---
# - name: create a disk
#   gcp_compute_disk:
#     name: 'disk-instance'
#     size_gb: 50
#     source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts'
#     zone: "{{ zone }}"
#     project: "{{ gcp_project }}"
#     auth_kind: "{{ gcp_cred_kind }}"
#     service_account_file: "{{ gcp_cred_file }}"
#     scopes:
#       - https://www.googleapis.com/auth/compute
#     state: present
#   register: disk

# - name: create a network
#   gcp_compute_network:
#     name: 'network-instance'
#     project: "{{ gcp_project }}"
#     auth_kind: "{{ gcp_cred_kind }}"
#     service_account_file: "{{ gcp_cred_file }}"
#     scopes:
#       - https://www.googleapis.com/auth/compute
#     state: present
#   register: network

# - name: create a address
#   gcp_compute_address:
#     name: 'address-instance'
#     region: "{{ region }}"
#     project: "{{ gcp_project }}"
#     auth_kind: "{{ gcp_cred_kind }}"
#     service_account_file: "{{ gcp_cred_file }}"
#     scopes:
#       - https://www.googleapis.com/auth/compute
#     state: present
#   register: address

# - name: create a instance
#   gcp_compute_instance:
#     state: present
#     name: test-vm
#     machine_type: n1-standard-1
#     disks:
#       - auto_delete: true
#         boot: true
#         source: "{{ disk }}"
#     network_interfaces:
#       - network: "{{ network }}"
#         access_configs:
#           - name: 'External NAT'
#             nat_ip: "{{ address }}"
#             type: 'ONE_TO_ONE_NAT'
#     zone: "{{ zone }}"
#     project: "{{ gcp_project }}"
#     auth_kind: "{{ gcp_cred_kind }}"
#     service_account_file: "{{ gcp_cred_file }}"
#     scopes:
#       - https://www.googleapis.com/auth/compute
#   register: instance

# - name: Wait for SSH to come up
#   wait_for: host={{ instance.address }} port=22 delay=10 timeout=60

# - name: Add host to groupname
#   add_host: hostname={{ instance.address }} groupname=new_instances
